### PR TITLE
Support an optional instance name, add flags explanation to readme

### PR DESCRIPTION
**Pull request by elseym**
* Adds a feature that allows to prepend OpenVPN status paths with instance
names / friendly names. Those will be exported under the additional label
'instance_name' and default to the respective status path if not set.
* Adds a new section to the readme explaining the command line flags.

### CODE REVIEW

**Comment by EdSchouten** [comment]
Hey! Thanks a lot for working on this!

General remark: for a traffic accounting system that we wrote ([promacct](https://github.com/kumina/promacct)) we also wanted to have the ability to attach labels to network interfaces and IP ranges (e.g., customer info).

Would it make sense to stick to promacct's approach and change the map to work the other way around? As in, to have one map entry per pathname and let that map to a set of additional labels that should be attached to the metrics. That way you could say:

```
... -openvpn.status_paths /some/path:customer=apple:sla=24x7:....
```

**Comment by elseym** [comment]
Hey Ed! Thanks for the quick response. :)

With this PR I wanted to add the 'friendly name' functionality while keeping the changeset small. But I like your suggestion, I'd also like to look into it during the next week. Do you think this can be done without major refactoring or should there be a separate PR?

**Comment by EdSchouten** [comment]
No need to create separate PRs! The tool is small enough that I don't mind reviewing changes of any size.

**Comment by elseym** [comment]
Alright 👍

**Comment by EdSchouten** [comment]
Closing this pull request due to inactivity. Feel free to submit a new pull request with updated changes in the future!

**Pull request closed without merging**
