### PR TITLE
Allow for individual user metrics to be optionally ignored

### PR DESCRIPTION
**Pull request by rajatvig**
This should partially help fix https://github.com/kumina/openvpn_exporter/issues/19

### CODE REVIEW

**Comment by NotAFile** [comment]
why was this closed and deleted?

**Comment by rajatvig** [comment]
@NotAFile Sorry, my bad. Have reopened it.

Was cleaning up my fork of it to do some more refactor with tests etc. Have some more work done, still to write tests etc.
Seeing some regression on an instance, investigating.

**Comment by rruu** [comment]
@rajatvig Hi, I tried your version https://github.com/rajatvig/openvpn_exporter, after second user connect with same login, exporter crashed with exception:

```
An error has occurred while serving metrics:

3 error(s) occurred:
* collected metric "openvpn_server_client_received_bytes_total" { label:<name:"common_name" value:"user1" > label:<name:"name" value:"vpn" > counter:<value:2.572237e+06 > } was collected before with the same name and label values
* collected metric "openvpn_server_client_sent_bytes_total" { label:<name:"common_name" value:"user1" > label:<name:"name" value:"vpn" > counter:<value:1.907445e+07 > } was collected before with the same name and label values
* collected metric "openvpn_server_route_last_reference_time_seconds" { label:<name:"common_name" value:"user1" > label:<name:"name" value:"vpn" > gauge:<value:1.569833662e+09 > } was collected before with the same name and label values
```

**Comment by rajatvig** [comment]
@rruu Could you open a bug for it on my fork? Will track it there. Had noticed some crashes on the VPN that I am using it for but hadn't yet dived into what condition caused it. This info is useful. Will try and fix once I have a few free cycles.

**Comment by rajatvig** [comment]
@rruu Have fixed that crash by keeping a list of recorded metrics

**Comment by BartVerc** [comment]
> @rajatvig Hi, I tried your version https://github.com/rajatvig/openvpn_exporter, after second user connect with same login, exporter crashed with exception:
> 
> ```
> An error has occurred while serving metrics:
> 
> 3 error(s) occurred:
> * collected metric "openvpn_server_client_received_bytes_total" { label:<name:"common_name" value:"user1" > label:<name:"name" value:"vpn" > counter:<value:2.572237e+06 > } was collected before with the same name and label values
> * collected metric "openvpn_server_client_sent_bytes_total" { label:<name:"common_name" value:"user1" > label:<name:"name" value:"vpn" > counter:<value:1.907445e+07 > } was collected before with the same name and label values
> * collected metric "openvpn_server_route_last_reference_time_seconds" { label:<name:"common_name" value:"user1" > label:<name:"name" value:"vpn" > gauge:<value:1.569833662e+09 > } was collected before with the same name and label values
> ```

Going to make some changes based on this PR, with fixing the double metric exception. As this [commit](https://github.com/rajatvig/openvpn_exporter/commit/fd2479407d5081aec85aaca23f0134dd7cf012ef) had the problem of only showing one line per metric. Fixed in PR#31.

**Comment by rajatvig** [comment]
Had the bug fixed in my fork but didn't port it as it seemed this repository was not in active maintenance. There are more changes I have in my fork that are larger refactorings.

**Pull request closed without merging**
